#!/bin/sh

pushd day1; ./runit; popd
pushd day2; ./runit; popd
pushd day3; ./runit; popd
pushd day4; ./runit; popd
pushd day5; ./runit; popd
pushd day6; ./runit; popd
pushd day7; ./runit; popd
pushd day8; ./runit; popd
pushd day9; ./runit; popd
